lhd_app_container_documents_dir: /var/documents

mariadb_connection_string: >-
  mysql://{{ lhd_secrets.mysql.lhd_app.user }}:{{ lhd_secrets.mysql.lhd_app.password }}@{{ lhd_secrets.mysql.lhd_app.host }}:{{ lhd_secrets.mysql.lhd_app.port }}/{{ lhd_secrets.mysql.lhd_app.dbname }}

cristal_url: >-
  {{
  "cristal.epfl.ch"
  if inventory_environment == "prod"
  else "cristal-test.epfl.ch"
  }}

openid_connect:
  test:
    # https://app-portal.epfl.ch/app-details/cf7bc1d1-c39d-455e-9de9-3da1398c4058
    base_url: https://login.microsoftonline.com/f6c2556a-c4fb-4ab1-a2c7-9e220df11c43/v2.0
    client_id: cf7bc1d1-c39d-455e-9de9-3da1398c4058
  prod:
    # https://app-portal.epfl.ch/app-details/4a30c695-3d0c-48a1-93d6-9410647934af
    base_url: https://login.microsoftonline.com/f6c2556a-c4fb-4ab1-a2c7-9e220df11c43/v2.0
    client_id: 4a30c695-3d0c-48a1-93d6-9410647934af

lhd_secrets: >-
  {{ lookup('pipe', 'keybase fs read /keybase/team/epfl_lhd/secrets_%s.yml'
  % inventory_environment)
  | from_yaml }}

image_tag: >-
  {{ "prod" if inventory_deployment_stage == "production"
  else "latest" }}

lil_url:
  test: https://lil-test.epfl.ch/
  prod: https://lil.epfl.ch/
